name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Windows target
      run: rustup target add x86_64-pc-windows-gnu

    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose
      
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release upload ${{ github.ref_name }} ./target/release/*.exe
